### ISSUE TITLE
デザインが変わってやがる。

### ISSUE THREAD

**Issue by HayatoDoi** [HayatoDoi/automatic-sakito#2]
デザインが変わってしまったため、スクレイピングがうまいこと動いていない可能性がある。

**Comment by miyzawa** [comment]
ワロタｗ

**Comment by HayatoDoi** [comment]
- check_new_question.py
問題なく動作

- turn_gacha.py
うまく動かない。

ガチャページがなんかおかしいため、運営の報告。

**Comment by HayatoDoi** [comment]
運営の報告結果。

明日(11月14日)修正するらしい。

修正後プログラムをアップデートする。

**Comment by HayatoDoi** [comment]
なんか動くようになっていたため close
